//
// Copyright 2026 Hewlett Packard Enterprise Development LP
//
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

syntax = "proto3";
package target_btree;

message Msg {
  message CreateCmd {
    bool feat_uint_key = 1;
    bool feat_embed_first = 2;
    bool inplace = 3;
    uint32 order = 4;
  }

  message CloseCmd {
  }

  message DestroyCmd {
  }

  message OpenCmd {
  }

  message UpdateCmd {
    uint32 entries_num = 1;
  }

  message IterCmd {
    uint32 entries_num = 1;
  }

  message QueryCmd {
  }

  message LookupCmd {
    uint32 entries_num = 1;
  }

  message DeleteCmd {
    uint64 entries_num = 1;
  }

  message DrainCmd {
    uint64 credits_num = 1;
  }

  message Command {
    oneof cmd {
      CreateCmd create = 1;
      OpenCmd open = 2;
      CloseCmd close = 3;
      DestroyCmd destroy = 4;
      UpdateCmd update = 5;
      IterCmd iter = 6;
      QueryCmd query = 7;
      LookupCmd lookup = 8;
      DeleteCmd delete = 9;
      DrainCmd drain = 10;
    }
  }

  repeated Command commands = 1;
}
